### ISSUE TITLE
Redesign of Mission Pinball Framework Website

### ISSUE THREAD

**Issue by ankianki** [missionpinball/missionpinball-website#6]
Hey, I have taken a deeper look at the website and would like to know if you would be interested in a redesign. Some key things I observed:

1. The website contains a lot of text which consumes space vertically and is a little difficult to read since there's a lot of info side by side in the range of sight. Additionally, it lacks a theme and it would be nice to have a visually appealing UI that can make the text easier to read. 
2. The website lacks a footer that can contain links from the header. 
3. Since there are a lot of bullet points, it would be nice to have these texts with an icon that can add an additional highlight to each point. 

These are just a few things that I thought could be improved with a new design. I have made a banner for your website as a first look into the new redesign. 
![Pinball](https://user-images.githubusercontent.com/17936995/107127866-5937ce00-68b9-11eb-91a3-9ed7e782b829.png)

**Comment by jabdoa2** [comment]
Hey, that looks awesome. I'm not much of a designer. A redesign or any improvements to the layout would be welcome!

**Comment by ankianki** [comment]
Hey, thanks! This is my progress so far, let me know what you think about it. You can also leave a comment on the design if you wish :) https://xd.adobe.com/view/8c313e5b-f6af-4307-96e4-6b3f12fa3574-d962/

**Comment by jabdoa2** [comment]
I like it! Only a small remark: We should make sure that we hold all rights for the images (i.e. the image of the pinball). Let me know if I can help with anything.

**Comment by ankianki** [comment]
Hey, thanks! Glad you like it :) The xd link has been updated. I can send you a list of the icons used and from where. Attribution to the author is needed but other than that they are all free to use. Let me know what you think and how we can proceed with this :)

**Comment by jabdoa2** [comment]
Looks like I forgot to answer here. Sorry for that! I like your design. Do you want to create a PR to modify the page or how should we proceed?

**Comment by toomanybrians** [comment]
Website redesign in progress: https://github.com/orgs/missionpinball/discussions/100
